apiVersion: v1
kind: Pod
metadata:
  namespace: qa
  name: myapp
  labels:
    app: tesla
spec:
  containers:
  - name: webapp
    image: mylandmarktech/java-web-app
    ports:
    - containerPort: 8080
